resources:
- name: z-qml-repo
  type: git
  source:
    uri: git@github.com:zapatacomputing/z-qml.git
    branch: master
    private_key: ((zapatabot-ssh))

- name: z-qml-image-latest
  type: registry-image
  source:
    tag: nightly
    repository: zapatacomputing/z-qml
    username: ((zapatabot-dockerhub-username))
    password: ((zapatabot-dockerhub-password))

jobs:

- name: publish-docker-image-latest
  serial: true
  plan:
  - in_parallel:   
    - get: z-qml-repo
      trigger: true
      params:
        unpack: true
  - task: docker-build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: concourse/oci-build-task
      params:
        CONTEXT: z-qml-repo/.
        DOCKERFILE: z-qml-repo/Dockerfile
      inputs:
        - name: z-qml-repo
          path: z-qml-repo
      outputs:
        - name: image
      run:
        user: root
        path: build
  - put: z-qml-image-latest
    params:
      image: image/image.tar

groups:
- name: build
  jobs:
  - publish-docker-image-latest
